### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by willfaught** [goccmack/gocc#23]
I'm getting a runtime panic for an index out of range when running gocc:

	$ gocc -o syntax -p syntax my.bnf
	panic: runtime error: index out of range
	
	goroutine 1 [running]:
	panic(0x25fba0, 0xc820014070)
		/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:464 +0x3e6
	github.com/goccmack/gocc/parser/lr1/items.NewItem(0x102, 0xc8200d8bc0, 0x0, 0xc8200e2e7f, 0x1, 0x2)
		/Users/Will/Developer/go/src/github.com/goccmack/gocc/parser/lr1/items/item.go:49 +0x7a3
	github.com/goccmack/gocc/parser/lr1/items.(*ItemSet).Closure(0xc820462c60, 0xc820462cc0)
		/Users/Will/Developer/go/src/github.com/goccmack/gocc/parser/lr1/items/itemset.go:139 +0x8d2
	github.com/goccmack/gocc/parser/lr1/items.(*ItemSet).Goto(0xc820368ea0, 0xc8200b592a, 0x1, 0xc820462c00)
		/Users/Will/Developer/go/src/github.com/goccmack/gocc/parser/lr1/items/itemset.go:196 +0x3dc
	github.com/goccmack/gocc/parser/lr1/items.GetItemSets(0xc8200e2f50, 0xc82000a600, 0xc8205febd0, 0x40)
		/Users/Will/Developer/go/src/github.com/goccmack/gocc/parser/lr1/items/itemsets.go:44 +0x29f
	main.main()
		/Users/Will/Developer/go/src/github.com/goccmack/gocc/main.go:113 +0xe51

The problem seems to be at parser/lr1/items/item.go:49 in NewItem:

	if prod.Body.Symbols[0].SymbolString() == "empty" {

The BNF was:

	literal: _integer | _float | _char | _string;
	_special: '(' | ')' | ',' | ';' | '[' | ']' | '`' | '{' | '}';

	_whitespace: _whitestuff { _whitestuff };
	_whitestuff: _whitechar | _comment | _ncomment;
	_whitechar: _newline | _vertab | _space | _tab | _uniWhite;
	_newline: _return _linefeed | _return | _linefeed | _formfeed;
	_return: '\r';
	_linefeed: '\n';
	_vertab: '\v';
	_formfeed: '\f';
	_space: ' ';
	_tab: '\t';
	_uniWhite: '\u0009' - '\u000D' | '\u0020' | '\u0085' | '\u00A0' | '\u1680' | '\u2000' - '\u200A' | '\u2028' | '\u2029' | '\u202F' | '\u205F' | '\u3000';

	_comment: _dashes [ _any { _any } ] _newline; // TODO: - _symbol
	_dashes: '-' '-' { '-' };
	_opencom: '{' '-';
	_closecom: '-' '}';
	_ncomment: _opencom _anyseq { _ncomment _anyseq } _closecom;
	_anyseq: { _any }; // TODO: - ( { _any } ( _opencom | _closecom ) { _any } )
	_any: _graphic | _whitechar;
	_anylim: _graphic | _space | _tab;
	_graphic: _small | _large | _symbol | _digit | _special | '"' | '\\';

	_small: _ascSmall | _uniSmall | '_';
	_ascSmall: 'a' - 'z';
	_uniSmall: _ascSmall; // TODO

	_large: _ascLarge | _uniLarge;
	_ascLarge: 'A' - 'Z';
	_uniLarge: _ascLarge; // TODO
	_symbol: _ascSymbol | _uniSymbol; // TODO: - (special | '_' | '"' | '\\')

	_ascSymbol: '!' | '#' | '$' | '%' | '&' | '⋆' | '+' | '.' | '/' | '<' | '=' | '>' | '?' | '@' | '\\' | '^' | '|' | '-' | '~' | ':';
	_uniSymbol: _ascSymbol; // TODO
	_digit: _ascDigit | _uniDigit;
	_ascDigit: '0' - '9';
	_uniDigit: _ascDigit; // TODO
	_octit: '0' - '7';
	_hexit: _digit | 'A' - 'F' | 'a' - 'f';

	varid: _varid;
	_varid: _small { _small | _large | _digit | '\\' }; // TODO: - _reservedid
	conid: _conid;
	_conid: _large { _small | _large | _digit | '\\' };
	_reservedid: 'c' 'a' 's' 'e' | 'c' 'l' 'a' 's' 's' | 'd' 'a' 't' 'a' | 'd' 'e' 'f' 'a' 'u' 'l' 't' | 'd' 'e' 'r' 'i' 'v' 'i' 'n' 'g' | 'd' 'o' | 'e' 'l' 's' 'e' | 'f' 'o' 'r' 'e' 'i' 'g' 'n' | 'i' 'f' | 'i' 'm' 'p' 'o' 'r' 't' | 'i' 'n' | 'i' 'n' 'f' 'i' 'x' | 'i' 'n' 'f' 'i' 'x' 'l' | 'i' 'n' 'f' 'i' 'x' 'r' | 'i' 'n' 's' 't' 'a' 'n' 'c' 'e' | 'l' 'e' 't' | 'm' 'o' 'd' 'u' 'l' 'e' | 'n' 'e' 'w' 't' 'y' 'p' 'e' | 'o' 'f' | 't' 'h' 'e' 'n' | 't' 'y' 'p' 'e' | 'w' 'h' 'e' 'r' 'e' | '_';

	varsym: _varsym;
	_varsym: _symbol { _symbol }; // TODO: - ':', - ( _reservedop | _dashes )
	consym: _consym;
	_consym: ':' { _symbol }; // TODO:  - _reservedop
	_reservedop: '.' '.' | ':' | ':' ':' | '=' | '\\' | '|' | '<' '-' | '-' '>' |  '@' | '~' | '=' '>';

	tyvar: _varid;
	tycon: _tycon;
	_tycon: _conid;
	tycls: _tycls;
	_tycls: _conid;
	modid: _modid;
	_modid: { _conid '.' } _conid;

	qvarid: [ _modid '.' ] _varid;
	qconid: [ _modid '.' ] _conid;
	qtycon: [ _modid '.' ] _tycon;
	qtycls: [ _modid '.' ] _tycls;
	qvarsym: [ _modid '.' ] _varsym;
	qconsym: [ _modid '.' ] _consym;

	_decimal: _digit { _digit };
	_octal: _octit { _octit };
	_hexadecimal: _hexit { _hexit };

	integer: _integer;
	_integer: _decimal | '0' 'o' _octal | '0' 'O' _octal | '0' 'x' _hexadecimal | '0' 'X' _hexadecimal;
	float: _float;
	_float: _decimal '.' _decimal [ _exponent ] | _decimal _exponent;
	_exponent: ('e' | 'E') [ '+' | '-' ] _decimal;

	_char: '\'' ( _graphic | _space | _escape ) '\''; // TODO: - ('\\' | '\\' ), - ( '\\' | '&' )
	string: _string;
	_string: '"' { _graphic | _space | _escape | _gap } '"'; // TODO: - ('"' | '\\')
	_escape: '\\' ( _charesc | _ascii | _decimal | 'o' _octal | 'x' _hexadecimal );
	_charesc: 'a' | 'b' | 'f' | 'n' | 'r' | 't' | 'v' | '\\' | '"' | '\\' | '&';
	_ascii: '^' _cntrl | '\x00' - '\x20' | '\x7f';
	_cntrl: _ascLarge | '@' | '[' | '\\' | ']' | '^' | '_';
	_gap: '\\' _whitechar { _whitechar } '\\';

	Module: Module2 Body;
	Module2: empty | "module" modid Module3 "where";
	Module3: empty | Exports;
	Body: "{" Body2 "}";
	Body2: ImpDecls ";" TopDecls | ImpDecls | TopDecls;

	ImpDecls: ImpDecl ImpDecls2;
	ImpDecls2: empty | ";" ImpDecl ImpDecls2;

	Exports: "(" Exports2 ")";
	Exports2: empty | Export Exports3 Exports4;
	Exports3: empty | "," Export Exports3;
	Exports4: empty | ",";

	Export: QVar
	| qtycon Export2
	| qtycls Export6
	| "module" modid;
	Export2: empty | [ "(" Export3 ")";
	Export3: empty | ".." | Export4;
	Export4: CName Export5;
	Export5: empty | "," CName Export5;
	Export6: empty | [ "(" Export7 ")";
	Export7: empty | ".." | Export8;
	Export8: QVar Export9;
	Export9: empty | "," QVar Export9;

	ImpDecl: "import" ImpDecl2 modid ImpDecl3 ImpDecl4 | empty;
	ImpDecl2: empty | "qualified";
	ImpDecl3: empty | "as" modid;
	ImpDecl4: empty | ImpSpec;

	ImpSpec: ImpSpec2 "(" ImpSpec3 ")";
	ImpSpec2: empty | "hiding";
	ImpSpec3: empty | Import ImpSpec4 ImpSpec5;
	ImpSpec4: empty | "," Import ImpSpec4;
	ImpSpec5: empty | ",";

	Import: Var
	| tycon Import2
	| tycls Import5;
	Import2: empty | "(" Import3 ")";
	Import3: empty | ".." | CName Import4;
	Import4: empty | "," CName Import4;
	Import5: empty | "(" Import6 ")";
	Import6: empty | ".." | Var Import7;
	Import7: empty | "," Var Import7;
	CName: Var | Con;

	TopDecls: empty | TopDecl TopDecls2;
	TopDecls2: empty | ";" TopDecl TopDecls2;
	TopDecl: "type" SimpleType "=" Type
	| "data" TopDecl2 SimpleType TopDecl3 TopDecl4
	| "newtype" TopDecl2 SimpleType "=" NewConstr TopDecl4
	| "Class" TopDecl5 tycls tyvar TopDecl6
	| "instance" TopDecl5 qtycls Inst TopDecl7
	| "default" "(" TopDecl8 ")"
	| "foreign" FDecl
	| Decl;
	TopDecl2: empty | Context "=>";
	TopDecl3: empty | "=" Constrs;
	TopDecl4: empty | Deriving;
	TopDecl5: empty | SContext "=>";
	TopDecl6: empty | "where" CDecls;
	TopDecl7: empty | "where" IDecls;
	TopDecl8: empty | Type TopDecl9;
	TopDecl9: empty | "," Type TopDecl9;

	Decls: "{" Decl Decls2 "}" | "{" "}";
	Decls2: empty | ";" Decl Decls2;
	Decl: GenDecl | FunLHS RHS | Pat RHS;

	CDecls: "{" CDecl CDecls2 "}" | "{" "}";
	CDecls2: empty | ";" CDecl CDecls2;
	CDecl: GenDecl | FunLHS RHS | Var RHS;

	IDecls: "{" IDecl IDecls2 "}" | "{" "}";
	IDecls2: empty | ";" IDecl IDecls2;
	IDecl: FunLHS RHS | Var RHS | empty;

	GenDecl: Vars "::" Context "=>" Type | Vars "::" Type | Fixity integer Ops | Fixity Ops | empty;

	Ops: Op Ops2;
	Ops2: empty | "," Op Ops2;
	Vars: Var Vars2;
	Vars2: empty | "," Var Vars2;
	Fixity: "infixl" | "infixr" | "infix";

	Type: BType "->" Type | BType;

	BType: BType AType | AType;

	AType: GTyCon | tyvar | "(" Type "," Type AType2 ")" | "[" Type "]" | "(" Type ")";
	AType2: empty | "," Type AType2;

	GTyCon: qtycon | "()" | "[]" | "(->)" | "(" "," GTyCon2 ")";
	GTyCon2: empty | "," GTyCon2;

	Context: Class | "(" ")" | "(" Class Context2 ")";
	Context2: empty | "," Class Context2;
	Class: qtycls tyvar | qtycls "(" tyvar AType Class2 ")";
	Class2: empty | AType Class2;
	SContext: SimpleClass | "(" ")" | "(" SimpleClass SContext2 ")";
	SContext2: empty | "," SimpleClass SContext2;
	SimpleClass: qtycls tyvar;

	SimpleType: tycon SimpleType2;
	SimpleType2: empty | SimpleType3;
	SimpleType3: empty | tyvar SimpleType3;
	Constrs: Constr Constrs2;
	Constrs2: empty | Constr Constrs2;
	Constr: Con Constr2 | Constr3 ConOp Constr3 | Con "{" Constr4 "}";
	Constr2: empty | Constr22 AType Constr2;
	Constr22: empty | "!";
	Constr3: BType | "!" AType;
	Constr4: empty | FieldDecl Constr5;
	Constr5: empty | "," FieldDecl Constr5;
	NewConstr: Con AType | Con "{" Var "::" Type "}";
	FieldDecl: Vars "::" Type | Vars "::" "!" AType;
	Deriving: "deriving" DClass | "deriving" "(" ")" | "deriving" "(" DClass Deriving2 ")";
	Deriving2: empty | "," DClass Deriving2;
	DClass: qtycls;

	Inst: GTyCon
	| "(" GTyCon Inst2 ")"
	| "(" tyvar "," tyvar Inst5 ")"
	| "[" tyvar "]"
	| "(" tyvar "->" tyvar ")";
	Inst2: empty | Inst3;
	Inst3: tyvar Inst4;
	Inst4: empty | tyvar Inst4;
	Inst5: empty | "," tyvar Inst5;

	FDecl: "import" CallConv Safety ImpEnt Var "::" FType
	| "import" CallConv ImpEnt Var "::" FType
	| Export CallConv ExpEnt Var "::" FType;
	CallConv: "ccall" | "stdcall" | "cplusplus" | "jvm" | "dotnet";
	ImpEnt: "[" string "]";
	ExpEnt: "[" string "]";
	Safety: "unsafe" | "safe";

	FType: FRType | FAType "->" FType;
	FRType: FAType | "()";
	FAType: qtycon AType FAType2 | qtycon;
	FAType2: empty | AType FAType2;

	FunLHS: Var APat FunLHS2 | Pat VarOp Pat | "(" FunLHS ")" APat FunLHS2;
	FunLHS2: empty | APat FunLHS2;

	RHS: "=" Exp "where" Decls | "=" Exp | GdRHS "where" Decls | GdRHS;

	GdRHS: Guards "=" Exp GdRHS | Guards "=" Exp;

	Guards: "|" Guard Guards2;
	Guards2: empty | "," Guard Guards2;
	Guard: Pat "<-" InfixExp | "let" Decls | InfixExp;

	Exp: InfixExp "::" Context "=>" Type | InfixExp "::" Type  | InfixExp;

	InfixExp: LExp QOp InfixExp | "-" InfixExp | LExp;

	LExp: //"\" APat LExp2 "->" Exp
	| "let" Decls "in" Exp
	| "if" Exp LExp3 "then" Exp LExp3 "else" Exp
	| "case" Exp "of" "{" Alts "}"
	| "do" "{" Stmts "}"
	| FExp;
	LExp2: empty | APat LExp2;
	LExp3: empty | ";";
	FExp: FExp AExp | AExp;

	AExp: QVar
	| GCon
	| literal
	| "(" Exp ")"
	| "(" Exp "," Exp AExp2 ")"
	| "[" Exp AExp2 "]"
	| "[" Exp "," Exp ".." Exp "]"
	| "[" Exp "," Exp ".." "]"
	| "[" Exp ".." Exp "]"
	| "[" Exp ".." "]"
	| "[" Exp "|" Qual AExp3 "]"
	| "(" InfixExp QOp ")"
	| "(" QOp InfixExp ")" // TODO: Missing "-" exception
	| QCon "{" AExp4 "}"
	| QCon "{" "}"
	| AExp "{" FBind AExp5 "}"; // TODO: Missing "-" exception
	AExp2: empty | "," Exp AExp2;
	AExp3: empty | "," Qual AExp3;
	AExp4: empty | FBind AExp5;
	AExp5: empty | "," FBind AExp5;

	Qual: Pat "<-" Exp | "let" Decls | Exp;

	Alts: Alt Alts2;
	Alts2: empty | ";" Alt Alts2;
	Alt: Pat "->" Exp "where" Decls | Pat "->" Exp | Pat GDPat "where" Decls | Pat GDPat | empty;

	GDPat: Guards "->" Exp GDPat | Guards "->" Exp;

	Stmts: Stmts2 Exp ";" | Stmts2 Exp;
	Stmts2: empty | Stmt Stmts2;
	Stmt: Exp ";" | Pat "<-" Exp ";" | "let" Decls ";" | ";";

	FBind: QVar "=" Exp;

	Pat: LPat QConOp Pat | LPat;

	LPat: APat | "-" integer | "-" float | GCon APat LPat2;
	LPat2: empty | APat LPat2;

	APat: Var
	| Var "@" APat
	| GCon
	| QCon "{" FPat APat2 "}"
	| QCon "{" "}"
	| literal
	| "_"
	| "(" Pat ")"
	| "(" Pat "," Pat APat3 ")"
	| "[" Pat APat3 "]"
	| "~" APat;
	APat2: empty | "," FPat APat2;
	APat3: empty | "," Pat APat3;

	FPat: QVar "=" Pat;

	GCon: "()" | "[]" | "(" "," GCon2 ")" | QCon;
	GCon2: empty | "," GCon2;

	Var: varid | "(" varsym ")";
	QVar: qvarid | "(" qvarsym ")";
	Con: conid | "(" consym ")";
	QCon: qconid | "(" GConSym ")";
	VarOp: varsym | "`" varid "`";
	QVarOp: qvarsym | "`" qvarid "`";
	ConOp: consym | "`" conid "`";
	QConOp: GConSym | "`" qconid "`";
	Op: VarOp | ConOp;
	QOp: QVarOp | QConOp;
	GConSym: ":" | qconsym;

Random question: Should `empty` be the last alternative, or does it matter?

**Comment by awalterschulze** [comment]
I don't see anything obviously wrong here.
I have encountered such an error before, maybe because I am not a fan of using empty.

Could you try to find the production that is causing the panic or at least a more minimal grammar?

**Comment by willfaught** [comment]
Good point. I'll try to pinpoint the syntax.

**Comment by mewmew** [comment]
> Good point. I'll try to pinpoint the syntax.

@willfaught Any luck trying to pinpoint the syntax causing the panic? Do you have a minimal grammar which reproduces the behaviour?

**Comment by willfaught** [comment]
No, sorry, I gave up.

**Comment by mewmew** [comment]
Reproduced with the following grammar.
```bnf
Foo
	:
	| "b" 
;
```

Gocc panic (rev goccmack/gocc@8d71da022fa2815162b089fcd105bbee1878d447):
```
u@x1 ~/D/a> gocc a.bnf 
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x5ffdc0, 0xc420010110)
	/home/u/go/src/runtime/panic.go:500 +0x1a1
github.com/goccmack/gocc/parser/lr1/items.NewItem(0x1, 0xc42000b3c0, 0x0, 0x63941a, 0x1, 0x1)
	/home/u/goget/src/github.com/goccmack/gocc/parser/lr1/items/item.go:49 +0x559
github.com/goccmack/gocc/parser/lr1/items.(*ItemSet).Closure(0xc420108060, 0xc42006c360)
	/home/u/goget/src/github.com/goccmack/gocc/parser/lr1/items/itemset.go:140 +0x4c0
github.com/goccmack/gocc/parser/lr1/items.GetItemSets(0xc420011f30, 0xc42006c360, 0xc4200e0420, 0x11)
	/home/u/goget/src/github.com/goccmack/gocc/parser/lr1/items/itemsets.go:35 +0x68
main.main()
	/home/u/goget/src/github.com/goccmack/gocc/main.go:113 +0x7e2
```

**Comment by mewmew** [comment]
@willfaught The culprit in the grammar was `LExp`.

```go
LExp
	: //"\" APat LExp2 "->" Exp
	| "let" Decls "in" Exp
```

**Comment by awalterschulze** [comment]
aha well this is something that gocc could report an error on instead of a panic :)
